import {
  Bell,
  BookOpen,
  ChefHat,
  CircleHelp,
  ClipboardList,
  Gift,
  Headphones,
  Heart,
  House,
  Lightbulb,
  MapPin,
  Menu,
  Search,
  Settings,
  ShoppingBag,
  ShoppingCart,
  UserRound,
  Users,
  Wheat,
  X,
  type LucideIcon,
} from "lucide-react";

export const brandIconMap = {
  home: House,
  recipes: BookOpen,
  products: ShoppingBag,
  ingredients: Wheat,
  courses: ChefHat,
  groupBuy: Gift,
  knowledge: Lightbulb,
  community: Users,
  store: MapPin,
  service: Headphones,
  account: UserRound,
  orders: ClipboardList,
  favorite: Heart,
  settings: Settings,
  cart: ShoppingCart,
  search: Search,
  notification: Bell,
  menu: Menu,
  close: X,
  help: CircleHelp,
} as const satisfies Record<string, LucideIcon>;

export type BrandIconKey = keyof typeof brandIconMap;
